In [2]:
## exploratory data analysis
import pandas as pd

In [6]:
## data import
train = pd.read_csv("../data/raw/Train.csv")
test = pd.read_csv("../data/raw/Test.csv")
var_defs = pd.read_csv("../data/raw/VariableDefinitions.csv")

In [13]:
## exploring the training data set
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 18506 entries, 0 to 18505
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tour_ID                18506 non-null  str
 1   country                18506 non-null  str
 2   age_group              18506 non-null  str
 3   travel_with            17431 non-null  str
 4   total_female           18504 non-null  float64
 5   total_male             18500 non-null  float64
 6   purpose                18506 non-null  str
 7   main_activity          18506 non-null  str
 8   info_source            18506 non-null  str
 9   tour_arrangement       18506 non-null  str
 10  package_transport_int  18506 non-null  str
 11  package_accomodation   18506 non-null  str
 12  package_food           18506 non-null  str
 13  package_transport_tz   18506 non-null  str
 14  package_sightseeing    18506 non-null  str
 15  package_guided_tour    18506 non-null  str
 16  package_insurance      18506 non-null  str
 17  night_mainland         18506 non-null  int64
 18  night_zanzibar         18506 non-null  int64
 19  first_trip_tz          18506 non-null  str
 20  cost_category          18506 non-null  str
dtypes: float64(2), int64(2), str(17)
memory usage: 3.0 MB

In [10]:
train.describe()

       total_female    total_male  night_mainland  night_zanzibar
count  18504.000000  18500.000000    18506.000000    18506.000000
mean       0.936230      0.998757        9.141576        2.493516
std        1.215582      1.173177       14.127449        5.275156
min        0.000000      0.000000        0.000000        0.000000
25%        0.000000      1.000000        3.000000        0.000000
50%        1.000000      1.000000        6.000000        0.000000
75%        1.000000      1.000000       11.000000        4.000000
max       49.000000     58.000000      365.000000      240.000000

In [11]:
train.shape

(18506, 21)

In [12]:
train.head(10)

,Tour_ID,country,age_group,travel_with,total_female,total_male,purpose,main_activity,info_source,tour_arrangement,...,package_accomodation,package_food,package_transport_tz,package_sightseeing,package_guided_tour,package_insurance,night_mainland,night_zanzibar,first_trip_tz,cost_category
0,tour_id1hffseyw,ITALY,45-64,With Children,0.0,2.0,Visiting Friends and Relatives,Beach Tourism,"Friends, relatives",Package Tour,...,Yes,Yes,Yes,No,No,No,0,7,Yes,High Cost
1,tour_idnacd7zag,UNITED KINGDOM,25-44,With Spouse,1.0,1.0,Leisure and Holidays,Wildlife Tourism,"Travel agent, tour operator",Package Tour,...,Yes,Yes,Yes,No,No,No,0,7,Yes,High Cost
2,tour_id62vz7e71,UNITED STATES OF AMERICA,65+,With Spouse,1.0,1.0,Leisure and Holidays,Widlife Tourism,"Travel agent, tour operator",Package Tour,...,Yes,Yes,Yes,Yes,Yes,No,6,6,Yes,Higher Cost
3,tour_idrc76tzix,RWANDA,25-44,With Spouse and Children,3.0,1.0,Leisure and Holidays,Beach Tourism,"Radio, TV, Web",Independent,...,No,No,No,No,No,No,3,0,No,Lower Cost
4,tour_idn723m0n9,UNITED STATES OF AMERICA,45-64,Alone,0.0,1.0,Leisure and Holidays,Widlife Tourism,"Travel agent, tour operator",Package Tour,...,Yes,Yes,Yes,No,Yes,Yes,7,0,Yes,Higher Cost
5,tour_id8aylf7ba,FRANCE,25-44,With Spouse,1.0,1.0,Leisure and Holidays,Widlife Tourism,"Newspaper, magazines, brochures",Package Tour,...,Yes,Yes,No,No,No,No,14,7,Yes,High Cost
6,tour_idvcadicba,SWIZERLAND,25-44,With Spouse,1.0,1.0,Leisure and Holidays,Wildlife Tourism,"Newspaper, magazines, brochures",Independent,...,No,No,No,No,No,No,7,0,Yes,Normal Cost
7,tour_idfmavssxv,NIGERIA,25-44,Alone,0.0,1.0,Leisure and Holidays,Cultural Tourism,"Travel agent, tour operator",Independent,...,No,No,No,No,No,No,4,0,Yes,Low Cost
8,tour_id8oqlvjwr,UNITED KINGDOM,18-24,Alone,1.0,0.0,Leisure and Holidays,Cultural Tourism,"Friends, relatives",Independent,...,No,No,No,No,No,No,60,0,Yes,Normal Cost
9,tour_idy0blevrs,AUSTRALIA,45-64,With Spouse,1.0,1.0,Leisure and Holidays,Widlife Tourism,"Travel agent, tour operator",Package Tour,...,Yes,No,Yes,Yes,Yes,Yes,6,0,Yes,Higher Cost

In [19]:
b

              count   pct
travel_with    1075  5.81
total_male        6  0.03
total_female      2  0.01

In [22]:
# Checking for duplicates in training data
dups_train = train.duplicated().sum()
print(f"Number of duplicated rows : {dups_train}")

Number of duplicated rows : 0

In [23]:
## exploring the testing data set
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 6169 entries, 0 to 6168
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tour_ID                6169 non-null   str
 1   country                6169 non-null   str
 2   age_group              6169 non-null   str
 3   travel_with            5808 non-null   str
 4   total_female           6167 non-null   float64
 5   total_male             6168 non-null   float64
 6   purpose                6169 non-null   str
 7   main_activity          6169 non-null   str
 8   info_source            6169 non-null   str
 9   tour_arrangement       6169 non-null   str
 10  package_transport_int  6169 non-null   str
 11  package_accomodation   6169 non-null   str
 12  package_food           6169 non-null   str
 13  package_transport_tz   6169 non-null   str
 14  package_sightseeing    6169 non-null   str
 15  package_guided_tour    6169 non-null   str
 16  package_insurance      6169 non-null   str
 17  night_mainland         6169 non-null   int64
 18  night_zanzibar         6169 non-null   int64
 19  first_trip_tz          6169 non-null   str
dtypes: float64(2), int64(2), str(16)
memory usage: 964.0 KB

In [24]:
test.describe()

       total_female   total_male  night_mainland  night_zanzibar
count   6167.000000  6168.000000      6169.00000     6169.000000
mean       0.922491     1.017510         9.31172        2.585832
std        1.173067     1.526274        16.36690        5.465058
min        0.000000     0.000000         0.00000        0.000000
25%        0.000000     1.000000         3.00000        0.000000
50%        1.000000     1.000000         6.00000        0.000000
75%        1.000000     1.000000        11.00000        4.000000
max       30.000000    90.000000       664.00000      174.000000

In [26]:
test.shape

(6169, 20)

In [27]:
test.head(10)

,Tour_ID,country,age_group,travel_with,total_female,total_male,purpose,main_activity,info_source,tour_arrangement,package_transport_int,package_accomodation,package_food,package_transport_tz,package_sightseeing,package_guided_tour,package_insurance,night_mainland,night_zanzibar,first_trip_tz
0,tour_idynufedne,KOREA,25-44,Alone,0.0,1.0,Leisure and Holidays,Widlife Tourism,Others,Independent,No,No,No,No,No,No,No,7,4,Yes
1,tour_id9r3y5moe,UNITED KINGDOM,45-64,With Children,1.0,1.0,Leisure and Holidays,Conference Tourism,"Travel agent, tour operator",Package Tour,Yes,Yes,Yes,Yes,Yes,Yes,Yes,7,0,Yes
2,tour_idf6itml6g,ITALY,25-44,With Spouse,1.0,1.0,Leisure and Holidays,Beach Tourism,"Travel agent, tour operator",Package Tour,Yes,Yes,No,Yes,No,No,No,0,6,Yes
3,tour_id99u4znru,KENYA,25-44,Alone,0.0,1.0,Other,Beach Tourism,"Radio, TV, Web",Independent,No,No,No,No,No,No,No,3,4,No
4,tour_idj4i9urbx,ZAMBIA,25-44,Alone,0.0,1.0,Business,Widlife Tourism,"Radio, TV, Web",Independent,No,No,No,No,No,No,No,6,0,No
5,tour_ids94pi2qs,UGANDA,45-64,Alone,0.0,1.0,Visiting Friends and Relatives,Beach Tourism,"Friends, relatives",Independent,No,No,No,No,No,No,No,23,0,No
6,tour_id9xx2dq4e,ITALY,45-64,With Spouse and Children,1.0,2.0,Leisure and Holidays,Beach Tourism,"Travel agent, tour operator",Package Tour,Yes,Yes,Yes,Yes,No,Yes,Yes,0,14,Yes
7,tour_id9q7cbwf5,ZAMBIA,25-44,Alone,0.0,1.0,Business,Beach Tourism,"Friends, relatives",Independent,No,No,No,No,No,No,No,6,0,No
8,tour_id28uzu8li,UNITED KINGDOM,45-64,With Spouse,1.0,1.0,Leisure and Holidays,Widlife Tourism,"Friends, relatives",Package Tour,No,Yes,Yes,Yes,Yes,No,No,4,0,Yes
9,tour_idf7lvpips,NETHERLANDS,25-44,Alone,0.0,1.0,Business,Widlife Tourism,"Friends, relatives",Independent,No,No,No,No,No,No,No,2,0,No

In [28]:
test.tail(5)

,Tour_ID,country,age_group,travel_with,total_female,total_male,purpose,main_activity,info_source,tour_arrangement,package_transport_int,package_accomodation,package_food,package_transport_tz,package_sightseeing,package_guided_tour,package_insurance,night_mainland,night_zanzibar,first_trip_tz
6164,tour_id2deyfjhq,ZIMBABWE,25-44,Alone,0.0,1.0,Business,Wildlife Tourism,"Friends, relatives",Independent,No,No,No,No,No,No,No,2,0,No
6165,tour_idlenv2rio,DRC,25-44,Alone,0.0,1.0,Visiting Friends and Relatives,Hunting Tourism,"Friends, relatives",Independent,No,No,No,No,No,No,No,60,0,Yes
6166,tour_id7wwqrs0p,CANADA,25-44,Alone,0.0,1.0,Leisure and Holidays,Beach Tourism,"Friends, relatives",Package Tour,Yes,Yes,Yes,Yes,No,No,No,5,0,No
6167,tour_idx80vbw5a,CANADA,18-24,Alone,1.0,0.0,Visiting Friends and Relatives,Wildlife Tourism,"Friends, relatives",Independent,No,No,No,No,No,No,No,21,0,No
6168,tour_id8fkkwytb,KENYA,45-64,NaN,0.0,1.0,Meetings and Conference,Wildlife Tourism,"Friends, relatives",Independent,No,No,No,No,No,No,No,4,0,Yes

In [30]:
# Checking for missing testing data
missing_test = test.isnull().sum().sort_values(ascending=False)
missing_test_pct = (missing_test / len(test) * 100).round(2)
missing_summary = pd.concat([missing_test, missing_test_pct], axis=1, keys=['count', 'pct'])
missing_summary[missing_summary['count'] > 0]

              count   pct
travel_with     361  5.85
total_female      2  0.03
total_male        1  0.02

In [31]:
# Checking for duplicates in testing data
dups_test = test.duplicated().sum()
print(f"Number of duplicated rows : {dups_test}")

Number of duplicated rows : 0